name: Release README

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create README package
      run: |
        mkdir -p release_package
        cp README.md release_package/
        cd release_package
        zip -r readme_package.zip README.md

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: readme_package.zip
        path: release_package/readme_package.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: readme_package.zip

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0  # Version tag
        release_name: "Release v1.0.0"
        draft: false
        prerelease: false

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release_package/readme_package.zip
        asset_name: readme_package.zip
        asset_content_type: application/zip
